#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate and verify the exact MXFP4 E8M0 x E2M1 binary16 LUT."""

from __future__ import annotations

import argparse
import hashlib
import re
import struct
import sys
from pathlib import Path


START_MARKER = "// BEGIN GENERATED MXFP4 HALF LUT"
END_MARKER = "// END GENERATED MXFP4 HALF LUT"
MXFP4_VALUES = (
    (0, 0),
    (1, 0),
    (2, 0),
    (3, 0),
    (4, 0),
    (6, 0),
    (8, 0),
    (12, 0),
    (0, 1),
    (1, 1),
    (2, 1),
    (3, 1),
    (4, 1),
    (6, 1),
    (8, 1),
    (12, 1),
)
CANONICAL_SHA256 = (
    "4345e991f2ff74c3ac43cac4f31660c537a23ca92aa12367487e489cf6a91090"
)


def round_pow2_rne(value: int, shift: int) -> int:
    """Round nonnegative ``value * 2**shift`` to integer, ties to even."""
    if shift >= 0:
        return value << shift
    denominator = 1 << -shift
    quotient, remainder = divmod(value, denominator)
    twice_remainder = remainder << 1
    if twice_remainder > denominator or (
        twice_remainder == denominator and (quotient & 1)
    ):
        quotient += 1
    return quotient


def finite_half_bits(numerator: int, power: int, negative: int) -> int:
    """Convert ``(-1)**negative * numerator * 2**power`` exactly to binary16."""
    sign = 0x8000 if negative else 0
    if numerator == 0:
        return sign

    floor_exponent = numerator.bit_length() - 1 + power
    if floor_exponent < -14:
        fraction = round_pow2_rne(numerator, power + 24)
        if fraction >= 1024:
            return sign | 0x0400
        return sign | fraction

    unbiased_exponent = floor_exponent
    if unbiased_exponent > 15:
        return sign | 0x7C00
    significand = round_pow2_rne(
        numerator, power - unbiased_exponent + 10
    )
    if significand == 2048:
        unbiased_exponent += 1
        significand = 1024
    if unbiased_exponent > 15:
        return sign | 0x7C00
    return sign | ((unbiased_exponent + 15) << 10) | (significand - 1024)


def table_bits() -> list[int]:
    values: list[int] = []
    for exponent in range(256):
        if exponent == 255:
            # Canonical table representation of infinity times E2M1. The
            # shader still uses arithmetic for this row so GPU NaN payload
            # canonicalization remains exactly as before.
            values.extend(
                0x7E00 if numerator == 0
                else (0xFC00 if negative else 0x7C00)
                for numerator, negative in MXFP4_VALUES
            )
            continue
        # E2M1 magnitudes are integer numerators over two. E8M0 e==0 is
        # 2**-127; finite nonzero exponent bytes are 2**(e-127).
        scale_power = -127 if exponent == 0 else exponent - 127
        values.extend(
            finite_half_bits(numerator, scale_power - 1, negative)
            for numerator, negative in MXFP4_VALUES
        )
    if len(values) != 4096:
        raise AssertionError(f"expected 4096 entries, generated {len(values)}")
    return values


def packed_sha256(values: list[int]) -> str:
    if len(values) != 4096:
        raise ValueError(f"expected 4096 entries, got {len(values)}")
    packed = struct.pack("<4096H", *values)
    return hashlib.sha256(packed).hexdigest()


def validate_canonical(values: list[int]) -> None:
    digest = packed_sha256(values)
    if digest != CANONICAL_SHA256:
        raise ValueError(
            f"MXFP4 half-LUT SHA-256 {digest} != canonical {CANONICAL_SHA256}"
        )


def generated_block() -> str:
    values = table_bits()
    validate_canonical(values)
    lines = [
        START_MARKER,
        "// Generated by metal/generate_mxfp4_half_lut.py; do not edit by hand.",
        "// Index = (E8M0 exponent byte << 4) | E2M1 code.",
        "static constant ushort ds4_metal_mxfp4_half_lut[256][16] = {",
    ]
    for exponent in range(256):
        row = values[exponent * 16 : (exponent + 1) * 16]
        lines.append(
            "    { " + ", ".join(f"0x{bits:04x}u" for bits in row) + " },"
        )
    lines.extend(("};", END_MARKER))
    return "\n".join(lines)


def replace_generated_block(source: str, block: str) -> str:
    start = source.find(START_MARKER)
    end = source.find(END_MARKER)
    if start < 0 or end < 0 or end < start:
        raise ValueError("MXFP4 half-LUT generated-region markers are missing")
    end += len(END_MARKER)
    return source[:start] + block + source[end:]


def parse_checked_in_values(source: str) -> list[int]:
    start = source.find(START_MARKER)
    end = source.find(END_MARKER)
    if start < 0 or end < 0 or end < start:
        raise ValueError("MXFP4 half-LUT generated-region markers are missing")
    literals = re.findall(r"0x([0-9a-fA-F]{4})u", source[start:end])
    if len(literals) != 4096:
        raise ValueError(
            f"expected exactly 4096 checked-in LUT literals, found {len(literals)}"
        )
    return [int(literal, 16) for literal in literals]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify the checked-in table")
    mode.add_argument("--emit", action="store_true", help="print the generated table block")
    args = parser.parse_args()

    block = generated_block()
    if args.emit:
        print(block)
        return 0

    target = Path(__file__).resolve().with_name("moe.metal")
    source = target.read_text(encoding="utf-8")
    expected = replace_generated_block(source, block)
    if args.check:
        checked_in = parse_checked_in_values(source)
        validate_canonical(checked_in)
        if checked_in != table_bits():
            print(f"{target}: checked-in literals differ from exact RNE generation", file=sys.stderr)
            return 1
        if source != expected:
            print(f"{target}: MXFP4 half LUT is stale", file=sys.stderr)
            return 1
        print(
            f"{target}: MXFP4 half LUT is current "
            f"(4096 entries, sha256={packed_sha256(checked_in)})"
        )
        return 0

    target.write_text(expected, encoding="utf-8")
    print(f"updated {target} with 4096 MXFP4 half-LUT entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
