#!/usr/bin/env python3
"""Regenerate ds4_qwen4_unicode.inc, the codepoint classes of the Qwen3.8
("qwen35") pre-tokenizer regex, from the `regex` module's Unicode tables.
Use a current `regex` release; the generated header records its version.

Usage: python gen_qwen4_unicode.py > ../ds4_qwen4_unicode.inc
"""
import sys

import regex

CLASSES = {
    "letter": r"\p{L}",
    "mark": r"\p{M}",
    "number": r"\p{N}",
    "space": r"\s",
}


def main() -> None:
    out = sys.stdout
    out.write("/* Generated by gguf-tools/gen_qwen4_unicode.py from the `regex` module's\n")
    out.write(f" * Unicode tables (regex {regex.__version__}); codepoint classes for the\n")
    out.write(" * Qwen3.8 pre-tokenizer. */\n\n")
    out.write("typedef struct { uint32_t lo, hi; } ds4_qwen4_urange;\n\n")
    for index, (name, cls) in enumerate(CLASSES.items()):
        if index:
            out.write("\n")
        pat = regex.compile(cls, regex.V1)
        ranges = []
        lo = prev = None
        for cp in range(0x110000):
            m = False if 0xD800 <= cp <= 0xDFFF else pat.match(chr(cp)) is not None
            if m:
                if lo is None:
                    lo = cp
                prev = cp
            elif lo is not None:
                ranges.append((lo, prev))
                lo = None
        if lo is not None:
            ranges.append((lo, prev))
        out.write(f"static const ds4_qwen4_urange ds4_qwen4_{name}_ranges[] = {{\n")
        for i in range(0, len(ranges), 4):
            out.write("    " + " ".join(f"{{0x{a:05x}, 0x{b:05x}}}," for a, b in ranges[i:i + 4]) + "\n")
        out.write("};\n")


if __name__ == "__main__":
    main()
